FROM node:22-slim

WORKDIR /app

COPY nextjs-bff/package.json ./
RUN corepack enable && pnpm install

COPY nextjs-bff ./
RUN pnpm run build

ENV HOSTNAME=0.0.0.0
ENV PORT=3000
EXPOSE 3000

CMD ["pnpm", "start"]
